name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build step
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        include:
          - node-version: 16
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
    - name: Container action
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Tony
        LAST_NAME: MA
      uses: tonyma/github-container-action@main
      with:
        who-to-greet: Tony Ma 2
    - run: npm install
    - name: Javascript action
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Tony
        LAST_NAME: MA
      uses: tonyma/githubaction2@main
      with:
        who-to-greet: Tony Ma 3
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test