name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build step
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        include:
          - node-version: 16
            experimental: true
        exclude:
          - node-version: 12.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
    - name: Container action
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Tony
        LAST_NAME: MA
      uses: tonyma/github-container-action@main
      with:
        who-to-greet: Tony Ma 2
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  build2:
    needs: build
    name: build step 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        os: [windows-latest, macos-latest]
        include:
          - node-version: 16
            os: ubuntu-latest
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
    - name: Javascript action
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Tony
        LAST_NAME: MA
      uses: tonyma/githubaction2@main
      with:
        who-to-greet: Tony Ma 3
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  build3:
    needs: build
    name: build step 3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        os: [windows-latest, macos-latest]
        include:
          - node-version: 16
            os: ubuntu-latest
            experimental: true
        exclude:
          - node-version: 12.x
            os: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
    - name: Javascript action
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Tony
        LAST_NAME: MA
      uses: tonyma/githubaction2@main
      with:
        who-to-greet: Tony Ma 3
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  build4:
    needs: [build2, build3]
    name: build step 4
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - node-version: 18
            os: ubuntu-latest
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
    - name: Javascript action
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Tony
        LAST_NAME: MA
      uses: tonyma/githubaction2@main
      with:
        who-to-greet: Tony Ma 3
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test