name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build step
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [10.x, 12.x, 14.x]
        include:
          - node-version: 16
            os: macos-latest
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
    # - name: Hello World
    #   uses: tonyma/githubaction2@v3
    #   with:
        # who-to-greet: Tony Ma
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test