name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build step
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x, 14.x]
        include:
          - node-version: 16
            os: macos-latest
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
    - run: npm install
    - name: Hello World
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Tony
        LAST_NAME: MA
      uses: tonyma/githubaction2@main
      with:
        who-to-greet: Tony Ma 2
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test